"""Added Access column

Revision ID: 9317a9a590da
Revises: 15a32593b621
Create Date: 2021-11-07 21:50:55.227284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9317a9a590da'
down_revision = '15a32593b621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_access')
    # ### end Alembic commands ###
